### ISSUE TITLE
Gibraltar not showing up unless you zoom in

### ISSUE THREAD

**Issue by ghost** [ahalota/Leaflet.CountrySelect#4]
Hello! We have Gibraltar on our map but it is not visually available to select unless you zoom in on the map. Is there any way to fix the issue so that Gibraltar would be able to be visible without zooming in?

Thank you!

**Comment by ahalota** [comment]
Gibraltar wasn't listed as a country in the file I used as input here. You can add it to the drop down if you want following the instructions on the main page. I think the below should work as a template. If you look in line 2 of Leaflet.CountrySelect.js, you will see the variable that is used to define each country, you just need to add your country before you create your toolbar and it should be included.

```
//Version a) Update the main list of countries

L.CountrySelect.countries['Gibraltar'] = <GEOJSON INFO FOR GIBRALTAR>
